# Generated by Django 3.1.3 on 2020-12-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.cache


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True,
                                                    verbose_name='Updated At')),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted',
                 models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='Deleted At')),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='Sipariş Tarihi')),
                ('delivery_date', models.DateTimeField(blank=True, null=True,
                                                       verbose_name='Teslim Tarihi')),
                ('payment_type', models.CharField(blank=True,
                                                  choices=[['NAKIT', 'Nakit'],
                                                           ['CEK', 'Cek'],
                                                           ['KREDI_KARTI',
                                                            'Kredi Karti'],
                                                           ['ACIK_HESAP',
                                                            'Acik Hesap']],
                                                  max_length=32, null=True,
                                                  verbose_name='Tahsilat Türü')),
                ('order_type', models.CharField(blank=True, choices=[
                    ['STANDART', 'Standart'],
                    ['ANT_FUAR_2020', 'Ant Fuar 2020']], max_length=32,
                                                null=True,
                                                verbose_name='Sipariş Türü')),
                ('note', models.CharField(blank=True, max_length=256, null=True,
                                          verbose_name='Not')),
                ('state', models.CharField(blank=True,
                                           choices=[['Açık', 'Açık'],
                                                    ['Kapalı', 'Kapalı']],
                                           max_length=32, null=True,
                                           verbose_name='Sipariş Durumu')),
                ('total_amount',
                 models.FloatField(default=0, verbose_name='Toplam Tutar')),
                ('total_amount_with_vat', models.FloatField(default=0,
                                                            verbose_name='Toplam Tutar (KDVli)')),
                ('discount',
                 models.FloatField(default=0, verbose_name='İndirim')),
                ('additional_discount',
                 models.FloatField(default=0, verbose_name='Ek İndirim')),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='company', to='company.company',
                                   verbose_name='Firma')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='order_order_created_by',
                                                 to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='order_order_deleted_by',
                                                 to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='order_order_updated_by',
                                                 to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Updated By')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, core.cache.BaseCache),
        ),
    ]
