# Generated by Django 3.1.3 on 2020-12-06 13:59

from django.db import migrations, models

import core.enums


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[['Açık', 'Açık'],
                                                        ['Kapalı', 'Kapalı']],
                                   default=core.enums.OrderStateEnum['OPEN'],
                                   max_length=32, null=True,
                                   verbose_name='Sipariş Durumu'),
        ),
    ]
