# Generated by Django 3.1.3 on 2020-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_auto_20201206_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_package_count',
            field=models.FloatField(default=0,
                                    verbose_name='Toplam Paket Sayısı'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.FloatField(default=0,
                                    verbose_name='Toplam Sipariş Sayısı'),
        ),
    ]
