# Generated by Django 3.1.3 on 2020-12-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201206_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[['Nakit', 'Nakit'], ['Çek', 'Çek'], ['Kredi Kartı', 'Kredi kartı'], ['Açık Hesap', 'Açık hesap']], max_length=32, null=True, verbose_name='Tahsilat Türü'),
        ),
    ]
