# Generated by Django 3.1.3 on 2020-12-05 17:27

import core.cache
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('barcode_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='Barkod No')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Sipariş Tarihi')),
                ('quantity', models.FloatField(default=0, verbose_name='Sipariş Miktarı')),
                ('koli_adedi', models.IntegerField(blank=True, null=True, verbose_name='Koli Adedi')),
                ('koli_sayisi', models.IntegerField(blank=True, null=True, verbose_name='Koli Sayısı')),
                ('special_price', models.FloatField(default=0, verbose_name='Özel Fiyat')),
                ('delivery_type', models.CharField(blank=True, choices=[['Açık', 'Açık'], ['Hazır', 'Hazır'], ['Kapalı', 'Kapalı'], ['Teslim_Edildi', 'Teslim Edildi']], max_length=32, null=True, verbose_name='Teslimat Türü')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('payment_type', models.CharField(blank=True, choices=[['NAKIT', 'Nakit'], ['CEK', 'Cek'], ['KREDI_KARTI', 'Kredi Karti'], ['ACIK_HESAP', 'Acik Hesap']], max_length=32, null=True, verbose_name='Tahsilat Türü')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Not')),
                ('list_price', models.FloatField(default=0, verbose_name='Liste Fiyatı')),
                ('expo_price', models.FloatField(default=0, verbose_name='Fuar Fiyatı')),
                ('state', models.CharField(blank=True, choices=[['Açık', 'Açık'], ['Kapalı', 'Kapalı']], max_length=32, null=True, verbose_name='Ödeme Şekli')),
                ('total_amount', models.FloatField(default=0, verbose_name='Liste Fiyatı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Firma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_offer_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_offer_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Ürün')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_offer_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, core.cache.BaseCache),
        ),
    ]
