# Generated by Django 3.1.3 on 2021-01-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('company', '0002_auto_20201219_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.township', verbose_name='Mahalle'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_type',
            field=models.CharField(blank=True, choices=[['Nakit', 'Nakit'], ['Çek', 'Çek'], ['Kredi Kartı', 'Kredi kartı'], ['Açık Hesap', 'Açık hesap']], max_length=32, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Tel No'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Vergi No'),
        ),
    ]
