# Generated by Django 3.1.3 on 2020-12-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.cache


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True,
                                                    verbose_name='Updated At')),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted',
                 models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='Deleted At')),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity',
                 models.FloatField(default=0, verbose_name='Sipariş Miktarı')),
                ('package_count',
                 models.FloatField(blank=True, default=1, null=True,
                                   verbose_name='Koli Adedi')),
                ('list_price',
                 models.FloatField(default=0, verbose_name='Satış Fiyatı')),
                ('created_by', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='order_item_orderitem_created_by',
                                                 to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='order_item_orderitem_deleted_by',
                                                 to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Deleted By')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='order', to='order.order',
                                   verbose_name='Sipariş')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='product', to='product.product',
                                   verbose_name='Ürün')),
                ('updated_by', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='order_item_orderitem_updated_by',
                                                 to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Updated By')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, core.cache.BaseCache),
        ),
    ]
