# Generated by Django 3.1.3 on 2020-12-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0003_auto_20201206_2209'),
        ('order_item', '0004_auto_20201206_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='orderitem', to='order.order',
                                    verbose_name='Sipariş'),
        ),
    ]
