# Generated by Django 3.1.3 on 2021-01-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201219_1504'),
        ('product', '0001_initial'),
        ('order_item', '0005_auto_20201212_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='list_price',
            field=models.FloatField(default=0, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='package_count',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Package Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.product', verbose_name='Product'),
        ),
    ]
